# Generated by Django 4.2 on 2025-06-30 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0007_channel_scan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='logo_position',
            field=models.CharField(blank=True, help_text="Enter overlay position like 'x=10:y=10' or 'x=W-w-10:y=H-h-10'", max_length=100, null=True, validators=[django.core.validators.RegexValidator(message="Enter a valid overlay position like 'x=10:y=10' or 'x=W-w-10:y=H-h-10'.", regex='^x=(?:\\d+|W-w-\\d+):y=(?:\\d+|H-h-\\d+)$')]),
        ),
    ]
