# Generated by Django 4.2 on 2025-07-02 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0008_alter_channel_logo_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='logo_opacity',
            field=models.FloatField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='channel',
            name='audio_gain',
            field=models.FloatField(default=1.0, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
