# Generated by Django 4.2 on 2025-07-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0009_channel_logo_opacity_alter_channel_audio_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='aspect_ratio',
            field=models.CharField(choices=[('16:9', '16:9'), ('4:3', '4:3')], default='16:9', max_length=5),
        ),
    ]
