# Generated by Django 4.2 on 2025-10-10 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0014_alter_channel_bitrate_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='audio_bitrate',
            field=models.IntegerField(help_text='128k, 256k', null=True, validators=[django.core.validators.MinValueValidator(32000), django.core.validators.MaxValueValidator(256000)]),
        ),
        migrations.AlterField(
            model_name='channel',
            name='audio_pid',
            field=models.IntegerField(default=102, help_text='Audio PID', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='channel',
            name='buffer_size',
            field=models.IntegerField(help_text='4.8M,9.6M', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(10000000)]),
        ),
        migrations.AlterField(
            model_name='channel',
            name='pcr_pid',
            field=models.IntegerField(default=256, null=True, validators=[django.core.validators.MinValueValidator(32), django.core.validators.MaxValueValidator(8186)]),
        ),
        migrations.AlterField(
            model_name='channel',
            name='pmt_pid',
            field=models.IntegerField(default=4096, null=True, validators=[django.core.validators.MinValueValidator(32), django.core.validators.MaxValueValidator(8186)]),
        ),
        migrations.AlterField(
            model_name='channel',
            name='resolution',
            field=models.CharField(choices=[('1920x1080', '1080p (Full HD)'), ('1280x720', '720p (HD)'), ('1024x576', '576p (SD PAL 16:9)'), ('768x576', '576p (SD PAL 4:3)'), ('854x480', '480p (SD)'), ('640x360', '360p'), ('426x240', '240p')], default='1920x1080', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='service_id',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='channel',
            name='video_pid',
            field=models.IntegerField(default=101, help_text='Video PID', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
