# Generated by Django 4.2 on 2025-10-10 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0015_alter_channel_audio_bitrate_alter_channel_audio_pid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abr',
            name='resolution',
            field=models.CharField(choices=[('1920x1080', '1080p (Full HD)'), ('1280x720', '720p (HD)'), ('1024x576', '576p (SD PAL 16:9)'), ('768x576', '576p (SD PAL 4:3)'), ('854x480', '480p (SD)'), ('640x480', '480p'), ('640x360', '360p'), ('426x240', '240p')], max_length=10),
        ),
        migrations.AlterField(
            model_name='channel',
            name='audio_bitrate',
            field=models.IntegerField(blank=True, help_text='128k, 256k', null=True, validators=[django.core.validators.MinValueValidator(32000), django.core.validators.MaxValueValidator(256000)]),
        ),
        migrations.AlterField(
            model_name='channel',
            name='audio_pid',
            field=models.IntegerField(blank=True, default=102, help_text='Audio PID', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='channel',
            name='buffer_size',
            field=models.IntegerField(blank=True, help_text='4.8M,9.6M', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(10000000)]),
        ),
        migrations.AlterField(
            model_name='channel',
            name='output_type',
            field=models.CharField(blank=True, choices=[('hls', 'hls'), ('rtmp', 'rtmp'), ('udp', 'udp'), ('file', 'file')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='pcr_pid',
            field=models.IntegerField(blank=True, default=256, null=True, validators=[django.core.validators.MinValueValidator(32), django.core.validators.MaxValueValidator(8186)]),
        ),
        migrations.AlterField(
            model_name='channel',
            name='pmt_pid',
            field=models.IntegerField(blank=True, default=4096, null=True, validators=[django.core.validators.MinValueValidator(32), django.core.validators.MaxValueValidator(8186)]),
        ),
        migrations.AlterField(
            model_name='channel',
            name='resolution',
            field=models.CharField(blank=True, choices=[('1920x1080', '1080p (Full HD)'), ('1280x720', '720p (HD)'), ('1024x576', '576p (SD PAL 16:9)'), ('768x576', '576p (SD PAL 4:3)'), ('854x480', '480p (SD)'), ('640x480', '480p'), ('640x360', '360p'), ('426x240', '240p')], default='1920x1080', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='service_id',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='channel',
            name='video_bitrate',
            field=models.IntegerField(blank=True, help_text='2.4M, 4.8M', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(10000000)]),
        ),
        migrations.AlterField(
            model_name='channel',
            name='video_pid',
            field=models.IntegerField(blank=True, default=101, help_text='Video PID', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
