# Generated by Django 4.2 on 2025-03-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('input_type', models.CharField(choices=[('hls', 'hls'), ('udp', 'udp'), ('file', 'file')], max_length=10)),
                ('input_url', models.CharField(blank=True, max_length=500, null=True)),
                ('input_multicast_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('input_network', models.CharField(blank=True, max_length=100, null=True)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='uploads/input/')),
                ('output_type', models.CharField(choices=[('hls', 'hls'), ('rtmp', 'rtmp'), ('udp', 'udp'), ('file', 'file')], max_length=10)),
                ('output_url', models.CharField(blank=True, max_length=500, null=True)),
                ('output_multicast_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('output_network', models.CharField(blank=True, max_length=100, null=True)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='uploads/output/')),
                ('video_codec', models.CharField(choices=[('h264', 'H.264'), ('h265', 'H.265'), ('mpeg2', 'MPEG-2')], default='h264', max_length=50)),
                ('audio', models.CharField(choices=[('aac', 'AAC'), ('ac3', 'AC3'), ('mp2', 'MP2')], default='aac', max_length=50)),
                ('video_bitrate', models.IntegerField(help_text='2.4M, 4.8M')),
                ('audio_bitrate', models.IntegerField(help_text='128k, 256k')),
                ('buffer_size', models.IntegerField(help_text='4.8M,9.6M')),
                ('resolution', models.CharField(choices=[('1920x1080', '1080p (Full HD)'), ('1280x720', '720p (HD)'), ('1024x576', '576p (SD PAL 16:9)'), ('768x576', '576p (SD PAL 4:3)'), ('854x480', '480p (SD)'), ('640x360', '360p'), ('426x240', '240p')], default='1920x1080', max_length=10)),
                ('frame_rate', models.IntegerField(choices=[(24, '24 FPS'), (25, '25 FPS'), (30, '30 FPS'), (50, '50 FPS'), (60, '60 FPS')], default=30)),
                ('logo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('logo_position', models.CharField(blank=True, choices=[('top-left', 'top-left'), ('top-right', 'top-right'), ('bottom-left', 'bottom-left'), ('bottom-right', 'bottom-right')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
