# Generated by Django 4.2 on 2025-03-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channels',
            new_name='Channel',
        ),
    ]
