# Generated by Django 4.2 on 2025-06-17 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0004_channel_audio_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='service_id',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
