# Generated by Django 4.2 on 2025-06-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0006_channel_audio_pid_channel_video_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='scan_type',
            field=models.CharField(choices=[('progressive', 'Progressive'), ('interlaced', 'Interlaced')], default='progressive', max_length=20),
        ),
    ]
