# Generated by Django 4.2 on 2025-10-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0012_channel_bitrate_mode_channel_is_abr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='bitrate_mode',
            field=models.CharField(choices=[('cbr', 'CBR'), ('vbr', 'VBR')], default='vbr', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='video_codec',
            field=models.CharField(choices=[('libx264', 'H.264'), ('libx265', 'H.265'), ('mpeg2video', 'MPEG-2')], default='libx264', max_length=50),
        ),
    ]
