# Generated by Django 4.2 on 2025-10-10 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0013_alter_channel_bitrate_mode_alter_channel_video_codec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='bitrate_mode',
            field=models.CharField(choices=[('cbr', 'CBR'), ('vbr', 'VBR')], default='vbr', max_length=5),
        ),
        migrations.AlterField(
            model_name='channel',
            name='video_bitrate',
            field=models.IntegerField(help_text='2.4M, 4.8M', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(10000000)]),
        ),
    ]
